### ISSUE TITLE
IE Weapon values.

### ISSUE THREAD

**Issue by Doomgull** [breakinblocks/nutsandbolts2#107]
Vanilla bow: (resources take 60 seconds from server start to make)
~1 attack/sec
deals 9-10 damage with no enchants or enhancements, requires arrows as ammunition.
Power V enchanted deals "25" damage, looks more like 20-23 on dummy tests.
Infinity enchantment gives infinite ammo (as though arrows are a resource sink).
Mending enchant repairs it.
Can also set things on fire with proper enchantment, which deals another 1-5 damage from burning.

===Other weapons mimicking Vanilla bow stats, including enchantability===
Botania Livingwood bow: string in a mana pool.
Same as vanilla bow, but can repair durability via mana.

Botania Crystal Bow: needs elven portal in current NAB progression, or access to a molecular transformer after access to a blast furnace level of tech.
Functions like a Vanilla bow with built in Infinity, needs mana to make arrows, arrows have higher velocity than vanilla.

Mek Electric Bow: 10. Fuck this thing. Not putting any effort into this one, same as the others.

===Other non-enchantable non-vanilla ranged weapons===

Basic Laser Gun: 1. But mines obsidian and dirty fairly quickly? Shitty weapon of shitness.

Basic 100% Manyulyn Shuriken with no upgrades: 15 per hit, 19 with two quartz upgrades, didn't even try tricking it out. 2-3 attacks/seconds

Type's shuriken:  2 Manyblades/2 paper blades, 2 sets quartz, 24 dps in 15 damage shots as well, based on tests in creative. Can be upgrade further via leveling. Attack rate exceeds hit-cooldown-rate on a single mob by nearly 2.5x.

Ember's Blazing Ray: 7, 1 attack/second because charge time doesn't matter. Seems to ignite sometimes. Enchants don't impact it, don't see a way to boost damage but may just be my lack of knowledge on how ember works.

DE Bow of the Wyvern: 12 (no upgrades), gets beyond vanilla easily with upgrades.

DE Draconic Bow: 30 (no upgrades), 50 one damage upgrade, 70 two damage upgrades, 90 three damage upgrades, 120 1 speed, 150 2 speed, 180 3 speed. Not even attempting to say this is balanced, since DE stuff is clearly the highest tier in the pack and who cares about insanity at that point.

===And finally, IE===

IE Revolver: (steel, treated wood, iron, ammunition requires more metal and gunpowder, and possibly a machine to make cases unless you like hemorrhaging copper to make them.)
Max of 6 shots (12 shots manually loading with upgrade) and only reloads manually clicking ammunition into slots, or via speedloader 6 rounds at a time, but speedloader cannot reload all 12 if upgraded.
1.3 attacks/sec

Damage depends on ammunition:
==Normal Ammo-
Casull: 10 damage, (ammunition:1 iron, 1 gunpowder, 1 copper, and casings)
Armor-Piercing: 10 damage "ignoring armor", (ammunition: 1 iron, steel and constantan/tungsten nuggets, gunpowder, and casings)
==Special Ammo-
Buckshot: fires eight 2-damage bullets in a spread that rapidly diverges (ammunition: copper and 2 red dye and 4 paper, gunpowder, iron dust)
Dragon's Breath: fires twelve 3-damage bullets in a spread that rapidly diverges and that ignite for 1-5 damage over next 1-5 seconds, ignites do not stack (ammunition: gunpowder, 2 aluminum dust, copper and 2 red dye and 4 paper). Literally Point Blank range (within melee attack range of mobs) finally deals better-than-vanilla-bow-damage against dummy if reliably dumping 8 or more of the shot into center-mass AND ignite goes off. Tests against enemies intending to perform this type of attack could only be reliably triggered against a single foe if flying and lunging in and out to attack, or by face tanking mob hits. Basic AoE sword swings were more effective in groups with same tactics, as was a vanilla enchanted bow.

Shocking upgrade prevents endermen from teleporting for 2-3 seconds, but slightly reduces damage against bosses during tests for some reason.

IE Railgun: (8 electrum, more copper, treated wood, steel, and more stuff)
0.3-0.6 attacks/sec (depending on upgrade using 3 HV coils [steel and aluminum ingots] and 3 HV capacitors [block of redstone, block of lead, 3 steel and two aluminum ingots each])
Costs 800 RF/shots
Uses expensive ammunition:
-Iron rod: 10 damage, arc like bow, slower than arrow vanilla movement, costs two iron.
-Steel rod: 12 damage, arc like bow, slower than arrow vanilla movement, costs two steel.
-Aluminum rod: 9 damage, arc like crossbow, slower than vanilla arrow movement, costs two aluminum.
-Graphite Electrode: 16 damage, relatively flat arc, same as vanilla arrow movement, costs 8 coal coke per projectile and three separate processing steps with a long time component via coke oven/industrial coke oven, crusher, and then Squeezer, and then metal press.

And so we get to my point: Steel is accessible starting at same point as tool forge due to requirements, which transitions into Modern Era. Weapon is always worse than Vanilla bow for same advancement point and resource availability, but requires constant resource additions to use in form of ammunition. Also requires a separate special blueprint for the "good" ammunition type, which is only effective within 8 blocks or damage falls below normal ammunition due to spread. Said special ammunition also has a higher material cost per shot.

Using the same steel to make a ticon weapon in the tool forge results in a superior weapon from the start, and the gap only widens

For the railgun, it's worse than a vanilla bow when both are unupgraded to begin with, and only increases in power by using an incredibly expensive round: Graphite Electrodes need the Crusher to make as a gating tech, so gated into Modern Era/arc furnace tech. Plus the three other processor steps.

====Recommendations====

Casull/AP/Homing/Silver ammunition damage increase from 10 to 15. 
Buckshot increase from 2 to 3.
DragonsBreath increase from 3 to 4.
Phial stays at 1 as it doesn't impact potion effect.
Wolfpack direct hit stay at 6.
Wolfpack projectiles increase from 4 to 6.
Railgun multiplier increase from 1.0 to 1.8.

These changes bring the projectile damage more into line with where they fall, progression-wise, without nullifying the value vanilla enchanted bows bring vs the weapons, as well as making it so they're still usable mid-game. It also brings railguns above vanilla, per shot, but still below single-step upgraded wyvern and still below un-upgraded draconic bow damages.

#106

**Comment by Saereth** [comment]
Fine fine, lets #makeImmersiveGreatAgain.
