### ISSUE TITLE
MorphoTool and Enchiridion review

### ISSUE THREAD

**Issue by Saereth** [breakinblocks/nutsandbolts2#42]
Make sure all wrenches are available via morphotool

make sure all mod books are properly available via enchiridion

**Comment by Mofman1** [comment]
Morph-o-tool is working as intended, but enchiridion won't accept any of the manuals from any of mcjty's mods. RFTools Manual, RFTools Control Manual, RFTools Dimension Manual and Deep Resonance Manual. Also won't accept the Draconic Information Tablet. I'd suggest replacing Enchiridion with Akashic Tome by Vazkii. Works exactly the same as Morph-o-tool.

https://minecraft.curseforge.com/projects/akashic-tome

**Comment by Saereth** [comment]
can you preconfigure Akashic tome to have all of those books?

**Comment by Sentrus** [comment]
Enchiridion PR submitted.
