### ISSUE TITLE
/Dank/Null deleting items

### ISSUE THREAD

**Issue by Mofman1** [breakinblocks/nutsandbolts2#52]
Jesus Christ this is the dumbest bug report I've ever written but the /Dank/Null from P455w0rd's Things appears to be broken and deleting items at random.

**Comment by Saereth** [comment]
wtf.. lol

**Comment by Saereth** [comment]
Yeah... dont use it for now, will disable till its fixed
https://github.com/MinecraftModDevelopment/p455w0rdsThings/issues/25

**Comment by Doomgull** [comment]
Supposedly build 1.10.2-12.18.2.2151 resolves the /Dank/Null issue.

**Comment by Saereth** [comment]
This is fixed
