### ISSUE TITLE
Duplicate JEI overlays in multiplayer.

### ISSUE THREAD

**Issue by Sentrus** [breakinblocks/nutsandbolts2#53]
When on the server, I get duplicate JEI overlays. One is stuck on some random page, the other I can interact with. The non-functional one hides the search bar and makes it difficult to click on things. Previously it was only sometimes, but tonight I couldn't get rid of the damn thing.

Gennie also reported having the same issue.

**Comment by Saereth** [comment]
This issue needs to goto JEI's bug reporting, especially since I cant reproduce it to provide mezz more info

**Comment by Saereth** [comment]
please followup on this issue with anymore info you can provide https://github.com/mezz/JustEnoughItems/issues/607

**Comment by Sentrus** [comment]
Mezz pushed a fix. We need to update to build 373 or newer.
