### ISSUE TITLE
Current worldgen/seed not appropriate for server setting.

### ISSUE THREAD

**Issue by Sentrus** [breakinblocks/nutsandbolts2#59]
Several of us have done some exploring and found that the current worldgen is heavily, heavily ocean, resulting in very little land for people to explore or build on. I'm not sure what can be tweaked config wise, but all the  maps I've generated so far with our current RTG config are just occasional large islands in a vast ocean.

**Comment by Saereth** [comment]
let me know once you get a good geographicalcraft config and I'll update the server with it.
