### ISSUE TITLE
IC2 "Crushed Ores" cannot be smelted in TiCon Smeltery

### ISSUE THREAD

**Issue by Doomgull** [breakinblocks/nutsandbolts2#74]
The below IC2 Crushed ores can be smelted in a vanilla furnace, but have no recipe for smelting in the TiCon Smeltery:

-Crushed Copper Ore
-Crushed Gold Ore
-Crushed Iron Ore
-Crushed Lead Ore
-Crushed Silver Ore
-Crushed Tin Ore
-and all the Purified versions of the above.

Crushed Uranium doesn't have a furnace recipe, so shouldn't be included in the above recipe change request.

**Comment by Doomgull** [comment]
Also, need recipe for Zinc in the macerator.

**Comment by Saereth** [comment]
Adding recipes for crushed but not for purified, if you're that far in the chain already just finish the damn ore processing to dust ;p
