### ISSUE TITLE
Unused Config Files to remove.

### ISSUE THREAD

**Issue by Sentrus** [breakinblocks/nutsandbolts2#76]
Directories

**ORE**
**ResourcefulCrops**
**environmentaltech**
**etlunar**
**railcraft**
**simpleoregen**
**teamreborn**

Files

Bibliocraft.cfg
Bloodmoon.cfg
CompactSolars.cfg
CookingPlus.cfg
InfernalMobs.cfg
InvTweaks.cfg
InvTweaksRules.txt
InvTweaksTree.txt
NoMobSpawningonTrees.cfg
ZtonesReloaded.cfg
bitdrawers.cfg
chiseled_me.cfg
eiramoticons.cfg
glass_shards.cfg
goetia.cfg
harvestcraft.cfg
infinitylib.cfg
librarianlib.cfg
mobends.cfg
oretweaker.cfg
psionup.cfg
reccomplex.cfg
redstonepaste.cfg
refinedstorage.cfg
refraction.cfg
usefulnullifiers.cfg

**Comment by Saereth** [comment]
Purged
