### ISSUE TITLE
review/revamp cyberware

### ISSUE THREAD

**Issue by Saereth** [breakinblocks/nutsandbolts2#8]

**Comment by Saereth** [comment]
Original concept:
https://github.com/breakinblocks/nutsandbolts/issues/135

**Comment by Sentrus** [comment]
Done what I can with config changes, Infernal Mobs, and spawner blacklisting. To finish up balancing, Cyberware needs a more fitting later-game recipe for:

Surgery Chamber
Cyberware Charger
Scanner
Engineering Table
Radio Beacon
Radio Tower Components
Radio Kit

Optionally create a recipe for the Robosurgeon which is normally found only in Nether Fortress loot.
